### ISSUE TITLE
Filter the leagues through the backend and send it to the DB

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#149]
We need to get the information from the scores provider and filter using the information of the supported leagues that we have on the DB in the leagues_supported_filter endpoint.

### Tasks:

- [x] Get all leagues with the country information from the provider endpoint
- [x] Filter the results with the League IDS present in the DB:  leagues_supported_filter endpoint
- [x] Send the results to the DB: scores_league_list_dev & scores_league_list

### Details:

**Provider endpoint:**

https://soccer.sportmonks.com/api/v2.0/leagues?include=country

**Example Request:**

`        {
            "id": 2,
            "active": true,
            "type": "cup_international",
            "legacy_id": 11,
            "country_id": 41,
            "logo_path": "https://cdn.sportmonks.com/images/soccer/leagues/2.png",
            "name": "Champions League",
            "is_cup": true,
            "is_friendly": false,
            "current_season_id": 18346,
            "current_round_id": 259655,
            "current_stage_id": 77453621,
            "live_standings": true,
            "coverage": {
                "predictions": true,
                "topscorer_goals": true,
                "topscorer_assists": true,
                "topscorer_cards": true
            },
            "country": {
                "data": {
                    "id": 41,
                    "name": "Europe",
                    "image_path": "https://cdn.sportmonks.com/images/countries/png/short/eu.png",
                    "extra": null
                }
            }
        },`

**Fields to add to the league_list endpoint in the DB:**

             "id": 2,
            "type": "cup_international",
            "logo_path": "https://cdn.sportmonks.com/images/soccer/leagues/2.png",
            "name": "Champions League",
            "country": 
                    "id": 41,
                    "name": "Europe",
                    "image_path": "https://cdn.sportmonks.com/images/countries/png/short/eu.png",

<img width="1227" alt="Screenshot 2022-01-20 at 08 15 36" src="https://user-images.githubusercontent.com/37311649/150299375-7d03ba27-cac0-4c9c-9bd3-cbe7265a3e4f.png">
