### ISSUE TITLE
[FEATURE]: Integrate Ad System into Scores Platform

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2033]
### Goal
Integrate an advertising system within our scores platform, specifically targeting author-published content. The system will leverage four tables in Hasura `ad_types, ad_zones, ads, campaigns` to dynamically display ads based on active zones, campaign targeting, and regional availability. 

### Tasks
**Frontend Integration:**

Implement a system in Svelte to fetch and display ads from active zones.
Ads should only appear if they are active and match the targeting criteria (included/excluded ISO country codes).

### Implement the author and tag IDs into the targeting for creative and campaign targeting:

- [x] Author IDs
- [x] Tag IDs

Available on the creative and campaign `targeting` data.

```
{
  "device": [
    "mobile",
    "desktop"
  ],
  "country": {
    "exclude": [
      "AO",
      "AR",
      "BO",
      "BR",
      "CL",
      "CO",
      "CR",
      "CU",
      "DO",
      "EC",
      "SV",
      "GQ",
      "FR",
      "GT",
      "HN",
      "IN",
      "IT",
      "KE",
      "MX",
      "MZ",
      "NI",
      "PA",
      "PY",
      "PE",
      "PT",
      "PR",
      "RO",
      "SG",
      "ES",
      "SE",
      "GB",
      "US",
      "UY",
      "VE"
    ],
    "include": []
  },
  "authors": {
    "exclude": [],
    "include": [
      "1"
    ]
  },
    "tags": {
    "exclude": [],
    "include": []
  }
}
```

### Implementation Details

**Svelte Frontend:**

- [ ] Query ad_zones to find active zones. If status is active and ads_ids are present, proceed to display.

For each zone, query related ads and filter based on campaigns or ads targeting to handle country code availability.

Display ads in the UI, ensuring to check for device compatibility based on ad_types.devices.

**Frontend Logic for the Slider AD:**

- [x] AD delay of 10s before appearing;
- [x] [x] / close option with a 5s delay before appearing;
- [x] Pixel Perfect design;
- [x] Slide bottom effect;
- [x] Appear once per day for the same user;
- [x] CTA on video and button;
- [ ] Visible on the specified authors and tags;

**Backend Logic:**

- [x] Ensure ads are associated with the correct campaigns and zones based on campaigns.zones and campaigns.targeting.

### Acceptance Criteria

- [x] Active ad zones are correctly identified and displayed on the frontend.
- [x] Ads are only shown if they are active and match the targeting criteria, ensuring relevance to the viewer's location.
- [x] The system gracefully handles scenarios where no ads are available for display due to targeting restrictions or lack of active ads.

### FIGMA DESIGN:

https://www.figma.com/file/yI4P5GyrvTIobkkiBJghXv/Banner-ecommerce-design-(Community)?type=design&node-id=1815%3A1182&mode=design&t=Y1zj21ZBvtLOwE6s-1

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Incorrect video placeholder height;
- [ ] Incorrect Font CSS;
- [ ] Incorrect CTA height;
- [ ] X close option is appearing much after the 5s defined;
- [ ] CTA on video not working:
- [ ] 2 Different ads on the same campaign and zone with different GEOs not working;



![Image](https://github.com/Betarena/scores/assets/37311649/45d98c64-8d4e-44b6-b5d2-b6bf121751cd)

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Incorrect (X) position



![Image](https://github.com/Betarena/scores/assets/37311649/5353293d-b74b-4b2f-b373-a4dd9fcc107a)

**Comment by jonsnowpt** [comment]
@migbash 

Ads not being shown:

https://betarena.slack.com/archives/D02B1UHEECS/p1711708992993449

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] 1. White borders left and right;
- [ ] 2. Specific Author not being loaded;

1.

![Image](https://github.com/Betarena/scores/assets/37311649/fd2cd13f-5fbb-4a41-b7c8-10754d8315e0)

2.

![Image](https://github.com/Betarena/scores/assets/37311649/24aa694c-07e0-4e68-9b8a-bfaaad280158)

http://betarena-scores-platform.herokuapp.com/a/betarena-tennis-it/wta125k-antalya-turkiye-women-singles-polina-kudermetova-vs-jessica-bouzas-maneiro-2023-2024-pronostici-probabili-formazioni-e-consigli-per-le-scommesse-6ypq3pf3kzv3rd71711695676

**Comment by migbash** [comment]
> 1. White borders left and right;

Which borders ? Cannot see on `Figma`.

> 2. Specific Author not being loaded;

Not loaded because `http://[..]` is used. `https://[..]` must be used.

**Comment by jonsnowpt** [comment]
@migbash 

- [ ] Disable scroll when the ad is shown;
