### ISSUE TITLE
AD Engine Development Using Svelte

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2049]
#### Task Overview
We aim to develop an AD engine that dynamically loads advertisements based on geolocation, device type, and predefined AD zones within our platform. This engine will be built using Svelte and will interact with our Hasura backend to retrieve AD configurations and display them accordingly.

#### Requirements

- [x] 1. **Repository Setup:**

   - Create a new GitHub repository named `ad-engine-svelte`. This repository will host the code for our AD engine.

- [x] 2. **Domain Configuration:**

   - Configure the domain `ads.betarena.com` to serve the AD engine.

- [x] 3. **Geolocation and Device Type Targeting:**

   - Implement geolocation detection to load ads specific to user country codes.
   - Detect the user's device (mobile, tablet, or desktop) to tailor the ad display accordingly.

- [x] 4. **Hasura Integration:**

   - Use Hasura to define and manage AD zones. Each AD zone will be identified by a unique shortcode to integrate into the platform where ads should be displayed.

- [x] 5. **AD Engine Shortcode:**

   - Develop a shortcode system within Hasura `zone` table using the `tag` field. This tag will be used in the platform to load specific AD zones.

- [x] 6. **Code Snippet for AD Engine Integration:**

   - Provide a simple, embeddable code snippet that platforms can use to integrate the AD engine and display ads.

- [x] 7. **AD Loading Mechanism:**

   - ADs will be loaded from Hasura based on the configurations defined in the `types`, `zone`, `ad`, and `campaign` tables.

#### Hasura Tables Configuration
- **`types` Table:** Manage different types of ads (video, image, HTML, etc.).
- **`zone` Table:** Define AD zones available within the platform, including zone name, associated AD IDs, zone status, and placements.
- **`ad` Table:** Details about each ad, including type, name, creator, status, associated zone, targeting information, clicks, and campaign data.
- **`campaign` Table:** Used for creating campaigns, associating ads with zones, and specifying geotargeting.

#### Technical Specifications
- **Svelte Development:**
   - The front-end AD engine will be developed using Svelte, taking advantage of its reactivity and component-based architecture.
- **Geolocation and Device Detection:**
   - Utilize appropriate APIs or libraries for detecting user's geolocation and device type to ensure ads are displayed according to targeting specifications.
- **Hasura and GraphQL:**
   - Interact with Hasura via GraphQL to fetch ad configurations, including zone details, active campaigns, and ad metadata.

#### Example Code Snippet
```html
<!-- AD Engine Loader -->
<script src="https://ads.betarena.com/ad-engine-loader.js"></script>
<div data-ad-zone="ZONE_TAG_HERE"></div>
```
*Replace `ZONE_TAG_HERE` with the specific `tag` value from the `zone` table for the AD zone you wish to display.*

#### Acceptance Criteria
- A fully functional AD engine that dynamically loads ads based on user's location and device.
- AD zones are easily integrated into the platform using shortcodes defined in Hasura.
- Ads are displayed according to the targeting criteria specified in Hasura, with support for geolocation and device type filtering.
- The system gracefully handles the absence of ads for a given zone, device type, or geolocation, ensuring a smooth user experience.

#### Notes
- Ensure the AD engine is optimized for performance, with minimal impact on page load times.
- Rigorous testing is required to validate geolocation detection, device type targeting, and dynamic ad loading based on Hasura configurations.
- Collaboration with the backend team may be necessary to fine-tune Hasura configurations and GraphQL queries.

This task requires close attention to detail and a strong understanding of Svelte, Hasura, and ad targeting mechanics. Please review the specifications carefully and reach out with any questions or clarifications needed before proceeding.
