### ISSUE TITLE
[FEATURE]: Implement New Articles Listing Section in Frontend

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2085]
### 📝 Feature Request Description
We are developing a new section in our application that dynamically displays articles based on several contextual factors: user login status, device type (desktop or mobile/PWA), and user preferences. This task requires implementing different views and functionalities tailored to these contexts to enhance user engagement and provide personalized content access.

![Screenshot 2024-04-22 at 19 00 09](https://github.com/Betarena/scores/assets/37311649/885a1b5b-c92b-427f-8820-19519e3e5765)

🎬 INITIAL STATE
Preloader.

#### Requirements

1. **Different Views Based on Context:**
   - **Non-Logged-in Users on Mobile:** Display basic article list with an option to sign in.
   - **Logged-in Users on Mobile:** Show user's Betarena tokens (BTA), with conversion in USD, and a "Buy BTA" button.
   - **Non-Logged-in Users on Mobile PWA:** Implement an infinite loader for articles.
   - **Logged-in Users on Mobile PWA:** Display BTA balance, "Buy BTA" button, and use an infinite loader for articles.

2. **Common Elements Across Views:**
   - Logo.
   - Tabs for selecting article categories.
   - Articles list with:
     - Featured image (or placeholder if no image is available).
     - Author avatar.
     - Author name.
     - Read time.
     - Published date.
     - Article title.
     - Tags associated with the article.
   - Footer.
   - "View More" option or infinite scroll functionality to load additional articles.

3. **Data Handling:**
   - Data should be loaded from Redis cache primarily, with a fallback to load from Hasura if the cache is unavailable.
   - Articles should be sorted by published date. For logged-in users, prioritize articles related to the tags they follow.
   - Only show articles in the user-defined language.

4. **Content Filtering:**
   - Default content to load are forecasts, identified by specific tag IDs depending on the language:
     - EN: Forecast TAG ID
     - ES: Pronostico TAG ID
     - and so on for IT, RO, FR, PT, BR, SE.

5. **Technical Specifications:**
   - Frontend Framework: SvelteKit
   - Data Sources: Redis cache, Hasura GraphQL API
   - Hasura Endpoints to be used:
     - `authors_articles`
     - `authors_tags`
     - `authors_seo_details`
     - `authors_translations`

#### Implementation Steps

1. **Design Layouts:**
   - Create responsive layouts for each context (logged-in/out, mobile/PWA).
   - Ensure UI components like tabs and article lists adapt to different screen sizes and contexts.

2. **Fetch and Display Data:**
   - Implement data fetching logic with Redis as the primary source.
   - Add fallback logic to fetch from Hasura when needed.

3. **Integrate Infinite Scrolling:**
   - For mobile PWA views, implement infinite scrolling to load more articles dynamically.
   - For mobile non-PWA views, implement a "View More" button to load additional articles.

4. **Personalization and Localization:**
   - Personalize article listings based on user preferences for tags and language.
   - Use the user’s language settings to filter the articles.

5. **Testing:**
   - Test responsiveness across different devices.
   - Ensure correct functionality of the data fetching and fallback mechanisms.
   - Validate user-specific content loading and infinite scroll implementation.

6. **Deployment and Monitoring:**
   - Deploy updates to a staging environment for live testing.
   - Monitor application performance and user feedback for further adjustments.

### Themes:
Ensure the section supports both Light and Dark themes.

### 🔎 HTML SEO
The following content should be available on HTML to SEO purposes:

```
Author Name
Article title and link
Article tags and links
```

IMPORTANT:

This task includes a Footer CSS redesign.

URL: `{url}/a/content`

#### Acceptance criteria:

1. Responsive frontend implementation for the new articles section.
2. Integration with backend systems (Redis and Hasura).
3. Pull Request with all the changes, ready for review and testing.
4. SEO available
5. Language working correctly;
6. Article order correctly shown
7. Footer redesign complete;

### FIGMA:

https://www.figma.com/file/2hrUqV3U6a82pJYqGsAghH/Betarena?type=design&node-id=7185%3A23065&mode=design&t=Q6M43ZvP35zEnFxW-1

**Comment by jonsnowpt** [comment]
- [ ] 4. CSS Desktop: The width size of the articles list and lateral widget is fixed like in all the rest of the platform;
- [ ] 5. Buy and Balance links are not working;
- [ ] 6. Mobile: The tags have no right margin;
- [ ] 7. The bottom menu is not marking the filled icon to inform the user in wich section it is;
- [ ] 8. Infinite loader is not working on DESKTOP;
- [ ] 9. Mobile titles can have up to 3 lines;
- [ ] 10. Remove the tag analysis since we are not having that for now;
- [ ] 11. Mobile, Load More is not working;
- [ ] 12. Mobile, the + tag icon has incorrect proportion and size, should be 20 x 20 and it is 18 x 20
- [ ] 13. Mobile, the Betarena logo should be positioned left side not center;
- [ ] 14. Tablet, title can go up to 3 lines;
- [ ] 15. On tablet the tag approach is with the +4 not swipe;
- [ ] 16. Translations not working at this time;


4.

![Image](https://github.com/Betarena/scores/assets/37311649/f07f27b7-e86f-452d-9192-e85f72ee94d2)

13.

![Image](https://github.com/Betarena/scores/assets/37311649/ed3d1ae3-845b-400c-bfd8-8e6f28147cbc)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 17. Desktop: Incorrect width 
- [ ] 16. Not working
- [ ] 4. Not working
- [ ] 18. Incorrect navigation order;
- [ ] 19. Responsive is not working correctly;
- [ ] 11. Still not working;
- [ ] 21. When there is a title with only 2 lines, keep the tags in the same place on mobile; 

17.

![Image](https://github.com/Betarena/scores/assets/37311649/57ba8b80-4d59-463a-8808-f8c368a92aa6)

18.

![Image](https://github.com/Betarena/scores/assets/37311649/7bbb152e-fb43-45fb-a5f1-80fc6e208752)

19.

https://github.com/Betarena/scores/assets/37311649/54bde381-7f93-44c7-9a33-57667b8fc90f

21.

![Image](https://github.com/Betarena/scores/assets/37311649/67a7daae-3170-46e5-8e3d-591b75e89434)

**Comment by jonsnowpt** [comment]
- [ ] 23. On preloaders, getting 3 dark dots;
- [ ] 24. Width still incorrect;
- [ ] 25. Highlight the menu where the user is;
- [ ] 26. Wrong hover on the top menu in the light theme version;


23.

![Image](https://github.com/Betarena/scores/assets/37311649/dd0523a5-3688-43d0-9e67-7725fa981719)

24.

![Image](https://github.com/Betarena/scores/assets/37311649/b06172f0-df13-46c2-80c4-655faa30e962)

25.

![Image](https://github.com/Betarena/scores/assets/37311649/b5c4b326-ac91-404b-9a99-ea1e339a026a)

**Comment by jonsnowpt** [comment]
- [ ] 27. When changing languages the infinite loop of new articles stops working;
- [ ] 28. The tab underline should cover all the name;
- [ ] 29. Incorrect SEO details;
- [ ] 30. SCSS errors;
- [ ] 31. Links do not have a discernible name;


27.

https://github.com/Betarena/scores/assets/37311649/a9d65b3e-616e-44a7-952c-95061759ad01


28.

![Image](https://github.com/Betarena/scores/assets/37311649/349eaee9-3434-4d92-9be7-6e630ed333de)


29.

![Image](https://github.com/Betarena/scores/assets/37311649/f1b03d84-061e-4dc4-8252-48d05f00444f)

Correct:

```
query MyQuery {
  authors_seo_details {
    data
  }
}
```

```
{
  "data": {
    "authors_seo_details": [
      {
        "data": {
          "main_data": {
            "title": "The most insightful stories about {name} - Betarena",
            "noindex": false,
            "keywords": "{name}",
            "nofollow": false,
            "canonical": "{permalink}",
            "description": "{description}"
          },
          "opengraph": {
            "url": "{permalink}",
            "type": "website",
            "title": "The most insightful stories about {name} - Betarena",
            "images": [
              {
                "alt": "{name}",
                "url": "https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/Betarena_Media%2Fauthors%2Fseo%2Fbetarena_scores.jpeg?alt=media&token=e40eabaa-3fb7-4d8b-b888-d554ce0959f7",
                "width": 752,
                "height": 393
              }
            ],
            "locale": "en",
            "description": "{description}"
          },
          "twitter_card": {
            "site": "@betarenasocial",
            "image": "https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/Betarena_Media%2Fauthors%2Fseo%2Fbetarena_scores.jpeg?alt=media&token=e40eabaa-3fb7-4d8b-b888-d554ce0959f7",
            "title": "The most insightful stories about {name} - Betarena",
            "image_alt": "{name}",
            "description": "{description}"
          }
        }
      },
      {
        "data": {
          "main_data": {
            "title": "The sports content platform - Betarena",
            "noindex": false,
            "keywords": "sports, content, web3",
            "nofollow": false,
            "canonical": "{url}/a/content",
            "description": "Betarena is an sports platform where readers find the best content, and where expert and undiscovered voices can share their sports writing."
          },
          "opengraph": {
            "url": "{url}/a/content",
            "type": "website",
            "title": "The sports content platform - Betarena",
            "images": [
              {
                "alt": "Betarena Sports Content",
                "url": "https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/Betarena_Media%2Fauthors%2Fseo%2Fbetarena_scores.jpeg?alt=media&token=e40eabaa-3fb7-4d8b-b888-d554ce0959f7",
                "width": 752,
                "height": 393
              }
            ],
            "locale": "en",
            "description": "Betarena is an sports platform where readers find the best content, and where expert and undiscovered voices can share their sports writing."
          },
          "twitter_card": {
            "site": "@betarenasocial",
            "image": "https://firebasestorage.googleapis.com/v0/b/betarena-ios.appspot.com/o/Betarena_Media%2Fauthors%2Fseo%2Fbetarena_scores.jpeg?alt=media&token=e40eabaa-3fb7-4d8b-b888-d554ce0959f7",
            "title": "The sports content platform - Betarena",
            "image_alt": "Betarena Sports Content",
            "description": "Betarena is an sports platform where readers find the best content, and where expert and undiscovered voices can share their sports writing."
          }
        }
      }
    ]
  }
}

```

30.

![Image](https://github.com/Betarena/scores/assets/37311649/6d0e6220-39d3-4759-bda2-db446820d4e2)


31.

![Image](https://github.com/Betarena/scores/assets/37311649/f480d5de-1cb7-4c0b-b26d-69d22ecb76ac)

**Comment by jonsnowpt** [comment]
- [ ] 43. Missing translations in the other languages and it is "6 hours ago";
- [ ] 44. Scroll issues on Safari and Firefox;
- [ ] 45. We are loading unnecessary data into HTML, this data does not need to be loaded into this page since it is the article content;
- [ ] 35. Language filter stopped working correctly inside the tags;
- [ ] 32. Missing the reading time (It was missing from the desktop version design) DELAYED
- [ ] 46. Console errors dark and light scss;
- [ ] 42. Review header elements;



43.

![Image](https://github.com/Betarena/scores/assets/37311649/3b961286-98f4-4225-82c4-642020a3136d)

44.

https://github.com/Betarena/scores/assets/37311649/110c1555-1c9b-43ad-bc8b-d242bd38626e

45.

https://totheweb.com/learning_center/tools-search-engine-simulator/

![Image](https://github.com/Betarena/scores/assets/37311649/db771747-e0e8-4594-83f7-a5d9785dbc0a)


35.

https://betarena-scores-platform.herokuapp.com/a/tag/forecasts


46.

![Image](https://github.com/Betarena/scores/assets/37311649/2d5bcf10-4bc5-4081-bbea-20a7a1822039)

42.

![Image](https://github.com/Betarena/scores/assets/37311649/e338b0c0-cbd8-47c9-973a-b1c5d84c96dc)

**Comment by jonsnowpt** [comment]
- [ ] Still getting the CSS error Light and Dark CSS;


![Image](https://github.com/Betarena/scores/assets/37311649/11ffe60e-bae1-4dbd-ac3a-decaf378e29d)
