### ISSUE TITLE
[FEATURE]: Float Bottom Navigation Menu

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2087]
### Does a duplicate issue exist?

- [X] I have searched the existing issues

### 📝 Feature Request Description

We are planning to introduce a new bottom navigation menu to enhance navigation across different sections of the Betarena platform. This task involves creating a responsive and customizable bottom menu that adapts to user preferences and language settings, enabling quick access to various platform sections.

![Screenshot 2024-04-23 at 08 46 57](https://github.com/Betarena/scores/assets/37311649/9f59378b-a8a2-4c35-834d-21d92be649f2)

#### Requirements

1. **Menu Sections:**
   - **Scores and Statistics:** Direct users to the scores and statistics page.
   - **Sports Content:** Navigate to the sports content section.
   - **Competitions:** Access the competitions page where users can participate in sports competitions.
   - **User Profile:** Link to the user's profile page.

2. **Language-Specific Links:**
   - Ensure all navigation links are adapted to the user-selected language on the platform.

3. **Customizable Menu Order:**
   - Allow users to customize the order of the menu options.
   - This customization should reflect immediately on the home screen and other relevant parts of the platform.

4. **Persistence of Settings:**
   - For registered users, save these preferences in the Firestore database under the user profile section.

5. **Authentication Prompt for Unregistered Users:**
   - If an unregistered user attempts to customize the menu order, prompt them to register or log in.

6. **Technical Specifications:**
   - Frontend Framework: SvelteKit
   - Data Storage: Local Storage and Firestore Database.

7. **Design Requirements:**
   - The bottom menu should be responsive and accessible across all devices.
   - Ensure the design is in line with Betarena’s UI/UX standards.

#### Implementation Steps

1. **Implement Language-Specific Navigation:**
   - Fetch the user’s preferred language setting and adjust the link URLs accordingly.

2. **Menu Customization Feature:**
   - Implement functionality that allows users to drag and rearrange menu items.
   - Use appropriate frontend technologies to support dynamic rearrangement of menu items.

3. **Firestore Integration:**
   - For registered users, integrate with Firestore to store these preferences permanently under the user profile.

4. **Authentication Handling:**
   - Implement logic to detect if a user is registered when attempting to customize the menu.
   - Redirect unregistered users to a registration/login prompt when they try to save their menu preferences.

5. **Testing:**
   - Test the menu on various devices and browsers to ensure compatibility and responsiveness.
   - Validate that language settings and user preferences are correctly applied.

### ENDPOINTS:

`betarena_prod   navigation_menu   link`
`betarena_prod   translation   navigation_menu `

Query example:

```
query MyQuery {
  translation_navigation_menu {
    data
    lang
  }
}
```

#### Sections where the menu is present:

- [x] Scores home page
- [x] Competitions home page

IMPORTANT: The header should change accordingly in this sections.

#### Acceptance Criteria

- [x] Completed responsive bottom navigation menu with customization capabilities.
- [x] Integration with Firestore for saving user preferences.
- [x] Pull Request with all changes, submitted for review.

FIGMA:

https://www.figma.com/file/KLZ8I88MggBM3YpHi8jSzj/BTA-Betarena?type=design&node-id=1%3A3060&mode=design&t=h2Oe6v0xGiEnxJHS-1

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 1. Profile options are not working;
- [ ] 2. The bottom menu should only be available on 2 screens: Scores Home and Competitions Home;
- [ ] 3. Wrong icon color and missing the different color of the selected option;
- [ ] 4. Light theme with wrong icon colors and rounded corners;

3.

![Image](https://github.com/Betarena/scores/assets/37311649/cc6d37c8-b944-4b31-8b39-22dce874709b)

4.

![Image](https://github.com/Betarena/scores/assets/37311649/339725a9-7e47-4e93-8719-38ddad509bff)

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 6. Is PENDING;
- [ ] 7. Incorrect Avatar size it should be 25 x 25 and not 24, review also the other icons;

7.

![Image](https://github.com/Betarena/scores/assets/37311649/d313184c-400f-44c8-9c6a-cf8a4ec8f82f)

**Comment by Izobov** [comment]
@jonsnowpt it's 24 in Figma 


![Image](https://github.com/Betarena/scores/assets/54995954/a5fcfd85-c9bb-433d-a3cc-4d68f50c0f0b)
