### ISSUE TITLE
Create article for Sportstack

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#2272]
### Task: Implement Article Creation Feature on Betarena

**Objective**  
Develop the article creation functionality where users can write and publish articles, preview content, and configure settings before publication. The article will be linked to a specific Sportstack, and the user will be able to add tags and SEO content.

---

![Image](https://github.com/user-attachments/assets/de2ddcc8-eee4-46c6-a690-c24a6ea0bc68)

![Image](https://github.com/user-attachments/assets/e7088384-193a-4513-a96a-74117af099a6)

### **Feature Goals**:
1. **New Article Creation Section**:
    - Users will have a button to **create a new article**.
    - Once clicked, the user is taken to a new section with the **article editor**.
  
2. **Editor for Article Writing**:
    - **Editor** will be implemented using [**Tiptap**](https://tiptap.dev/product/editor).
    - The editor will support:
        - Headings
        - Bold
        - Italic
        - Strikethrough
        - Text Justification
        - Bullet lists
        - Numeric lists
        - Links (default **no-follow** unless user has a specific role)
        - Code
        - Image uploads (images should be uploaded, not URL-only).
    - **Auto-save**:
        - The editor will automatically save the document on each change or every 10 seconds.
        - **Title** is a required field with a minimum of 50 words.

3. **Publishing an Article**:
    - Upon clicking **Publish**, a popup will show a preview of the content.
    - The popup will also allow users to:
        - **Select a Sportstack** from a dropdown (where the article will be published).
        - **Add tags** for the article.
        - **Configure SEO** settings (title, description, noindex, nofollow, etc.).
        - **Add a thumbnail** image for the article.
    - **SEO Content**:
        - The user will be able to input SEO metadata:
            - Title
            - Description
            - Keywords
            - Canonical URL
            - OpenGraph and Twitter card metadata.
    - Once **published**, the article will be added to the selected **Sportstack** and saved to the **Hasura database**.

---

### **Technical Details**:

1. **Tiptap Editor**:
   - Add the necessary extensions to support headings, bold, italic, strikethrough, justification, bullet lists, numeric lists, links (with the condition of no-follow), code, and image uploads.

2. **Editor UI**:
   - Auto-save feature to save the article draft every 10 seconds or after every change.
   - Enforce a title with at least **50 words** before publishing.

3. **Publishing Workflow**:
   - When the user presses **Publish**:
     - A popup preview of the article content will appear.
     - Users can customize the publication settings, including **tags**, **SEO metadata**.
   - After confirmation, the article will be saved to the database and linked to the chosen **Sportstack**.

---

### **Hasura Integration**:

- The article will be added to the **Hasura** table: `betarena_prod.authors.articles`.
  
  **Table Structure**:
  
  - `id`: `integer`, primary key, default: `nextval(‘authors.articles_id_seq’::regclass)`
  - `seo_details`: `jsonb`, nullable
  - `lang`: `text`, nullable
  - `permalink`: `text`, primary key, unique
  - `data`: `jsonb`, nullable (contains article content like title, body)
  - `status`: `text`, nullable (set as **published**)
  - `published_date`: `timestamp with time zone`, nullable (timestamp when the article is published)
  - `tags`: `jsonb`, nullable (array of tag IDs)
  - `author_id`: `integer`, nullable (ID of the user who created the article)
  - `updated_at`: `timestamp with time zone`, nullable (timestamp of the last update)

**Example Article Structure in Hasura**:

- **SEO** (`seo_details`):
    ```json
    {
        "main_data": {
            "title": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024",
            "noindex": false,
            "keywords": "Forecasts, ATP, Chengdu, Zhou Yi, Tseng Chun-hsin",
            "nofollow": false,
            "canonical": "https://scores.betarena.com/a/betarena-tennis/zhou-yi-vs-tseng-chun-hsin-betting-tip-2024",
            "description": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024 – Exciting predictions for the Round of 32 match."
        },
        "opengraph": {
            "url": "https://scores.betarena.com/a/betarena-tennis/zhou-yi-vs-tseng-chun-hsin-betting-tip-2024",
            "type": "website",
            "title": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024",
            "images": [
                {
                    "alt": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024",
                    "url": "https://example.com/tennis_match.png",
                    "width": 752,
                    "height": 393
                }
            ],
            "locale": "en_US",
            "description": "Exciting predictions for the match at Chengdu Open."
        },
        "twitter_card": {
            "site": "@betarenasocial",
            "image": "https://example.com/tennis_match.png",
            "title": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024",
            "image_alt": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024",
            "description": "Exciting predictions for the Round of 32 match at Chengdu Open."
        }
    }
    ```

- **Article Data** (`data`):
    ```json
    {
        "title": "Zhou Yi vs Tseng Chun-hsin Betting Tip 2024",
        "content": "<h2>Introduction</h2><p>Zhou Yi and Tseng Chun-hsin face off in Chengdu...</p>"
    }
    ```

- **Tags** (`tags`):
    ```json
    [1648, 1667, 8749]
    ```

- **Author ID**: `1`

---

### **Steps**:

1. **Frontend**:
   - Set up a button to **create a new article** that opens the Tiptap editor.
   - Implement the article **editor** with support for text formatting, image uploads, links, etc.
   - Add **auto-save** functionality (save on every change or every 10 seconds).
   - **Preview and customizations** popup when publishing (tags, SEO, thumbnail).
   - **Dropdown for Sportstack selection** when publishing.
   
2. **Backend**:
   - Add the necessary endpoints to:
     - **Save drafts** (called on each auto-save or change).
     - **Publish article**:
       - Save the article content to the **Hasura** database.
       - Link the article to the selected **Sportstack**.
       - Include SEO data, tags, and publish date.
       - Handle the **permalink** generation based on the title.
   
---

### **Design Reference**:
- The designs you provided (attached) will guide the **UI flow**:
  - Dropdown for Sportstack selection.
  - Buttons for adding tags, SEO, and publishing.
  - Preview and customization pop-up before final publishing.

### ACCEPTANCE CRITERIA

- [ ] User to be able to create a new article;
- [ ] Editor integration;
- [ ] Upload image send images to the correct cloud storage folder;
- [ ] Tags system working correctly;
- [ ] Save animation/information available;
- [ ] Article cached;
- [ ] Draft saves while editing the article;
- [ ] Option to select other sportstack;
- [ ] SEO correctly added;
- [ ] Correct integration with the DB;

**Comment by Felipe-Rafael-Rosa** [comment]
I think this will help you.

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by jonsnowpt** [comment]
@Izobov 

- [ ] 1. Publish options should not be on the top of the keypad when the user is adding content to the article;
- [ ] 2. The title should add lines in the bottom, not disappearing into the right side in just one line;
- [ ] 3. The options that do not work on the title should be disabled (darker color) in the case of the dark theme, or lighter color in the case of the light theme;
- [ ] 4. The link option does not work correctly when the editor is on the top of the keypad;


1.2.3.4
https://github.com/user-attachments/assets/1667b714-2b98-46bf-ab56-eabe25bf53dc

**Comment by Izobov** [comment]
8. script error from add engine and svelte componente from that lib. Because on test env adds or turned off

**Comment by jonsnowpt** [comment]
@Izobov 

## ❗️ Revision / Issues

<details close>
  <summary>[1] Substack domain issues</summary>
  <br/>

![Image](https://github.com/user-attachments/assets/fa360e67-74ec-4532-83a1-293f6d4ddded)



  **📝 Description(s)**
  
The domain CSS has something wrong and it is also not changing when editing the name.


  **🟧 Update(s)**


</details>
<details close>
  <summary>[2] Substack delete on settings popup confirmation</summary>
  <br/>

![Image](https://github.com/user-attachments/assets/a3c83304-04cf-4fc9-97e6-0a25c9492469)



  **📝 Description(s)**
  
We are missing the popup confirmation popup.


  **🟧 Update(s)**


</details>
