### ISSUE TITLE
Newsletter sendgrid integration

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#250]
:sparkles: **Newsletter** :sparkles:

As a Betarena user
I want  to be able to submit my email to the betarena mailing list
so that I can get the latest updates of the platform in my email

We should integrate the Sendgrid snippet that allows users to be part of our existing mailing lists. This snipped should differ depending on the language where it is available.

Since there are limitations on how the CSS can be customized we should try to get it the most approximate possible.

### Tasks:

- [x] Apply the design for desktop, tablet, and mobile;
- [x] Integrate the Iframes respecting the Figma design;
- [x] Integrate the Iframes respecting the correct langs;

### Code:

**EN**

<iframe src="https://cdn.forms-content.sg-form.com/959f35f0-8a5e-11ec-ae12-6ab0b90e93b0"/>

**ES**

<iframe src="https://cdn.forms-content.sg-form.com/e2e80a33-947e-11ec-9a6f-bab7bbd1e44a"/>

**IT**

<iframe src="https://cdn.forms-content.sg-form.com/f6daf19c-947f-11ec-9a6f-bab7bbd1e44a"/>

**BR**

<iframe src="https://cdn.forms-content.sg-form.com/6a180301-9480-11ec-9a6f-bab7bbd1e44a"/>

**PT**

<iframe src="https://cdn.forms-content.sg-form.com/ae8bbec3-9480-11ec-9a6f-bab7bbd1e44a"/>

### Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena---Working?node-id=4142%3A165625

<img width="1481" alt="Screenshot 2022-02-23 at 08 00 25" src="https://user-images.githubusercontent.com/37311649/155280550-97603fe2-ecac-4688-a219-db588ee3d4d5.png">
