### ISSUE TITLE
Story - Create LiveScore

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#91]
:sparkles: **LiveScore** :sparkles:

As a Betarena user
I want  to be able to check live results
so that I can get info on the different matches happening on every day

Since we already have the data endpoint on Firebase we just need to apply the design and add the data on the widget:

### Tasks:

- [x] New Independent Repository;
- [x] CSS for all Desktop, Tablet, and Mobile;
- [x] Allow navigation throughout the days;
- [x] Option to see all and Live matches ;
- [x] Translations from Hasura working correctly;
- [ ] Calendar option working that will request data from the historic database;
- [ ] Historic DB should use the Redis DB for cached results;
- [x] SEO - Match and Betting Tip Links should be readable by the search engines;
- [x] SEO - Livescore Expression on all lang should be readable by the search engines;
- [x] League ordered should use the Hasura order information [leagues_filtered_country];

### Data endpoints from Firebase:

livescores_table
  livescores_2days
  livescores_2daysago
  livescores_3days
  livescores_3daysago
  livescores_4days
  livescores_now
  livescores_today
  livescores_tomorrow
  livescores_yesterday

### Design:

https://www.figma.com/file/4SlIPyxRBX2qg1eLaPUk9U/BetArena---Working?node-id=32%3A1635

![Screenshot 2021-12-23 at 08 38 45](https://user-images.githubusercontent.com/37311649/147212730-08093f12-4996-4520-ad8b-2a73f5ff5023.png)
